SELECT
`sentence-all`.`release_date` AS `release_date`,
`sentence-all`.`pr_site` AS `pr_site`,
`sentence-all`.`Targetyear(s)` AS `Targetyear(s)`,
`sentence-all`.`ArticleTargetYear` AS `ArticleTargetYear`,
`sentence-all`.`sentence-carbon` AS `sentence-carbon`,
`sentence-all`.`full_text` AS `full_text`,
`sentence-all`.`PressReleaseMonth` AS `PressReleaseMonth`,
`sentence-all`.`PressReleaseFullClean` AS `PressReleaseFullClean`,
`sentence-all`.`sentence-renewables` AS `sentence-renewables`,
`sentence-all`.`sentence-suppliers` AS `sentence-suppliers`,
`sentence-all`.`sentence-gender` AS `sentence-gender`,
`sentence-all`.`Company` AS `Company`,
`sentence-all`.`Annual Report Date` AS `Annual Report Date`,
`sentence-all`.`title` AS `title`,
`sentence-all`.`emails` AS `emails`,
`sentence-all`.`sentence-other` AS `sentence-other`,
`sentence-all`.`Source link` AS `Source link`,
`sentence-all`.`Source Date` AS `Source Date`,
`sentence-all`.`PressReleaseFullCleanstep1` AS `PressReleaseFullCleanstep1`,
`sentence-all`.`sentence-waste` AS `sentence-waste`,
`sentence-all`.`source` AS `source`,
`sentence-all`.`sentence-water` AS `sentence-water`,
`sentence-all`.`PressReleaseYear` AS `PressReleaseYear`,
`sentence-all`.`ticker` AS `ticker`,
`sentence-all`.`SentenceTargetYear` AS `SentenceTargetYear`,
`sentence-all`.`Target sentence` AS `Target sentence`,
`sentence-all`.`upload-date` AS `upload-date`,
`sentence-all`.`id` AS `id`,
`sentence-all`.`PageURL` AS `PageURL`,
`sentence-all`.`DocURL` AS `DocURL`,
`sentence-all`.`DocTitle` AS `DocTitle`,
`sentence-all`.`DocName` AS `DocName`,
`sentence-all`.`Target Sentence Page` AS `Target Sentence Page`,
`company_universe`.`x` AS `x`,
`company_universe`.`Member of the S&P500` AS `Member of the S&P500`,
`company_universe`.`Member of the Russell 1000 Index` AS `Member of the Russell 1000 Index`,
`company_universe`.`Scraping code set up ?` AS `Scraping code set up ?`,
`company_universe`.`Ticker(s)` AS `Ticker(s)`,
`company_universe`.`PR Agency` AS `PR Agency`,
`company_universe`.`Domain` AS `Domain`,
`company_universe`.`Company global/main press - news release site URL` AS `Company global/main press - news release site URL`,
`company_universe`.`Subscribed to press releases esgroadmap@gmail.com ?` AS `Subscribed to press releases esgroadmap@gmail.com ?`,
`company_universe`.`Subscribed to press releases jameskijani@gmail.com ?` AS `Subscribed to press releases jameskijani@gmail.com ?`,
`company_universe`.`Plain text press release subscription possible? (yes/no)` AS `Plain text press release subscription possible? (yes/no)`,
`company_universe`.`Company annual reports page URL` AS `Company annual reports page URL`,
`company_universe`.`Company annual report 2020 URL of pdf document (including 10-k)` AS `Company annual report 2020 URL of pdf document (including 10-k)`,
`company_universe`.`Company sustainability / ESG reports page URL` AS `Company sustainability / ESG reports page URL`,
`company_universe`.`Company Sustainability / ESG report 2020 URL of pdf document` AS `Company Sustainability / ESG report 2020 URL of pdf document`,
`company_universe`.`Country` AS `Country`,
`company_universe`.`sector code #1 (NAICS)` AS `sector code #1 (NAICS)`,
`company_universe`.`sector name #1 (NAICS)` AS `sector name #1 (NAICS)`,
`company_universe`.`sector code #2 (NAICS)` AS `sector code #2 (NAICS)`,
`company_universe`.`sector name #2 (NAICS)` AS `sector name #2 (NAICS)`,
`company_universe`.`sector code #3 (NAICS)` AS `sector code #3 (NAICS)`,
`company_universe`.`sector name #3 (NAICS)` AS `sector name #3 (NAICS)`,
`company_universe`.`sector code #4 (NAICS)` AS `sector code #4 (NAICS)`,
`company_universe`.`sector name #4 (NAICS)` AS `sector name #4 (NAICS)`,
`company_universe`.`sector code #5 (NAICS)` AS `sector code #5 (NAICS)`,
`company_universe`.`sector name #5 (NAICS)` AS `sector name #5 (NAICS)`,
`company_universe`.`WORKED BY:` AS `WORKED BY:`,
`company_universe`.`COMMENTS / NOTES` AS `COMMENTS / NOTES`,
`company_universe`.`Carbon sentence available ?` AS `Carbon sentence available ?`
FROM 
`esgroadmap-dumb`.`sentence-all` JOIN `esgroadmap-dumb`.`company_universe` ON `sentence-all`.`company` = `company_universe`.`company`
